version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  one:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run: echo "Hello World"

workflows:
  first:
    jobs:
      - one

