version: 2.1


jobs:
  build:
    working_directory: ~/project
    docker:
      - image: "circeci/python:3.9.1"
    steps:
      - checkout
      - run: python3 classes_full.py
    tests:
      working_directory: ~/project
      docker:
        - image: "circeci/python:3.9.1"
      steps:
        - checkout
        - run: python3 test_deck.py

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build