version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  pytest:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run: pip install pytest
      - run: echo pytest
  isort:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run: echo isort **/*.py -c -v
  flake8:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run: echo flake8
workflows:
  first:
    jobs:
      - pytest
      - isort
      - flake8

