version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  pytest:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run: pip install pytest
      - run: pytest
  isort:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run: pip install isort
      - run: echo isort *.py -c -v
  flake8:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8
workflows:
  first:
    jobs:
      - pytest
      - isort
      - flake8

